//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "organizer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id:         i64,
    #[sea_orm(unique)]
    pub user_id:    i64,
    pub phone:      String,
    pub is_delete:  bool,
    pub createtime: DateTime,
    pub updatetime: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rental_request::Entity")]
    RentalRequest,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::rental_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RentalRequest.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
