//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::ActivityType;
use super::sea_orm_active_enums::RequestStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rental_request")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub organizer_id: i64,
    pub venue_id: i64,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub activity_type: ActivityType,
    #[sea_orm(column_type = "Text")]
    pub request_comments: String,
    pub status: RequestStatus,
    pub createtime: DateTime,
    pub updatetime: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizer::Entity",
        from = "Column::OrganizerId",
        to = "super::organizer::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizer,
    #[sea_orm(
        belongs_to = "super::venue::Entity",
        from = "Column::VenueId",
        to = "super::venue::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Venue,
}

impl Related<super::organizer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizer.def()
    }
}

impl Related<super::venue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Venue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
