//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "activity_type")]
pub enum ActivityType {
    #[sea_orm(string_value = "all")]
    All,
    #[sea_orm(string_value = "exhibition")]
    Exhibition,
    #[sea_orm(string_value = "seminar")]
    Seminar,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "request_status")]
pub enum RequestStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "accepted")]
    Accepted,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "finished")]
    Finished,
    #[sea_orm(string_value = "canceled")]
    Canceled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_gender")]
pub enum UserGender {
    #[sea_orm(string_value = "male")]
    Male,
    #[sea_orm(string_value = "female")]
    Female,
    #[sea_orm(string_value = "nonbinary")]
    Nonbinary,
    #[sea_orm(string_value = "prefer_not_to_say")]
    PreferNotToSay,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_status")]
pub enum UserStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "ban")]
    Ban,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "venue_state")]
pub enum VenueState {
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "unpublished")]
    Unpublished,
}
