//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::UserGender;
use super::sea_orm_active_enums::UserStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub username: String,
    pub email: String,
    pub avatar: Option<String>,
    pub gender: Option<UserGender>,
    pub introduce: Option<String>,
    pub is_show: Option<bool>,
    pub is_delete: Option<bool>,
    pub status: Option<UserStatus>,
    pub createtime: Option<DateTime>,
    pub updatetime: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::lessor::Entity")]
    Lessor,
    #[sea_orm(has_one = "super::organizer::Entity")]
    Organizer,
}

impl Related<super::lessor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lessor.def()
    }
}

impl Related<super::organizer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
