//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "venue_image_uri")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub venue_id: i64,
    pub title: String,
    pub uri: String,
    pub comment: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::venue::Entity",
        from = "Column::VenueId",
        to = "super::venue::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Venue,
}

impl Related<super::venue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Venue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
