//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use super::sea_orm_active_enums::VenueState;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "venue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub lessor_id: i64,
    pub name: String,
    pub description: String,
    pub address: String,
    pub capacity: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub images: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub allow_activity: Json,
    pub state: VenueState,
    pub createtime: DateTime,
    pub updatetime: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::lessor::Entity",
        from = "Column::LessorId",
        to = "super::lessor::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Lessor,
    #[sea_orm(has_many = "super::rental_request::Entity")]
    RentalRequest,
}

impl Related<super::lessor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lessor.def()
    }
}

impl Related<super::rental_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RentalRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
